# p10k-config.zsh — Powerlevel10k user config loader
# Provides:     none (~/.p10k.zsh configures the prompt)
# Requires:     ~/.p10k.zsh (optional — generated by `p10k configure`; no-op if absent)
# Side-effects: source ~/.p10k.zsh
# Load-order:   LAST (after all plugins, just before the prompt renders)

# Powerlevel10k configuration
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
